route:
  receiver: telegram
  group_by: ['alertname', 'instance']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h

receivers:
  - name: telegram
    telegram_configs:
      - bot_token_file: /etc/alertmanager/telegram_token
        chat_id: 760376143
        send_resolved: true
        parse_mode: ''
        message: |-
          {{ if eq .Status "firing" }}🔥 ПРОБЛЕМА{{ else }}✅ РЕШЕНО{{ end }}
          {{ range .Alerts -}}
          {{ if .Annotations.summary }}{{ .Annotations.summary }}{{ else }}{{ .Labels.alertname }}{{ end }}
          {{ end }}
